#!/usr/bin/env python3
"""
eip2612pa/_render.py — internal render helper called by audit.sh.
Reads a JSON report from stdin and renders in the requested format.
CLI args: contract=... network=... chain_id=... net_label=... explorer_link=...
          bytecode_size=... format=md|json|txt
"""
import sys, os, json

KVS = {}
for arg in sys.argv[1:]:
    if "=" in arg:
        k, v = arg.split("=", 1)
        KVS[k] = v

report = json.load(sys.stdin)
report["contract"] = KVS.get("contract", report.get("contract", "?"))
report["net_label"] = KVS.get("net_label", report.get("net_label", "?"))
report["explorer_link"] = KVS.get("explorer_link", report.get("explorer_link", "#"))
fmt = KVS.get("format", "md")


def sev_label(s):
    if s == 0: return "NOT EIP-2612"
    if s <= 30: return "LOW"
    if s <= 60: return "MEDIUM"
    if s <= 80: return "HIGH"
    return "CRITICAL"


if fmt == "json":
    print(json.dumps(report, indent=2))
elif fmt == "txt":
    print("eip2612pa — EIP-2612 permit audit report")
    print(f"  Contract:        {report['contract']}")
    print(f"  Network:         {report['net_label']}")
    print(f"  Bytecode:        {report.get('bytecode_size', 0):,} bytes")
    print(f"  Has permit:      {report.get('has_permit', False)}")
    print(f"  Has nonces:      {report.get('has_nonces', False)}")
    print(f"  Has DOMAIN_SEP:  {report.get('has_domain_separator', False)}")
    print(f"  Overall:         {report.get('overall_score', 0)} / 100 ({sev_label(report.get('overall_score', 0))})")
    print(f"  Checks:          {len(report.get('checks', []))}")
    print()
    for c in report.get("checks", []):
        sym = {"PASS": "[OK]", "FAIL": "[FAIL]", "WARN": "[WARN]", "NOT_FOUND": "[??]",
               "SKIP": "[skip]", "N/A": "[n/a]", "INFO": "[info]"}.get(c["verdict"], "[?]")
        print(f"  {sym}  #{c['id']}  {c['name']}")
        print(f"             evidence: {c['evidence']}")
        print()
else:
    out = []
    out.append("# eip2612pa — EIP-2612 permit audit report")
    out.append("")
    out.append(f"**Contract:** [{report['contract']}]({report['explorer_link']})")
    out.append(f"**Network:** {report['net_label']}")
    out.append(f"**Bytecode size:** {report.get('bytecode_size', 0):,} bytes")
    out.append(f"**Has permit():** {'yes (selector 0xd505accf)' if report.get('has_permit') else 'no'}")
    out.append(f"**Has nonces():** {'yes (selector 0x7ecebe00)' if report.get('has_nonces') else 'no'}")
    out.append(f"**Has DOMAIN_SEPARATOR():** {'yes (selector 0x3644e515)' if report.get('has_domain_separator') else 'no'}")
    out.append("")
    overall = report.get("overall_score", 0)
    label = sev_label(overall)
    verdict = report.get("verdict", "")
    out.append(f"## Overall score: {overall} / 100 ({label} · {verdict})")
    out.append("")
    out.append(f"## Checks ({len(report.get('checks', []))})")
    out.append("")
    if not any(c["verdict"] in ("FAIL", "NOT_FOUND") for c in report.get("checks", [])):
        out.append("_All checks PASS. Contract implements EIP-2612 correctly._")
        out.append("")
    for c in report.get("checks", []):
        sym = {"PASS": "PASS", "FAIL": "FAIL", "WARN": "WARN", "NOT_FOUND": "NOT_FOUND",
               "SKIP": "SKIP", "N/A": "N/A", "INFO": "INFO"}.get(c["verdict"], c["verdict"])
        out.append(f"### {sym} — #{c['id']} {c['name']}")
        out.append("")
        out.append(f"- Evidence: {c['evidence']}")
        out.append("")
    out.append("---")
    out.append("")
    out.append(f"Generated by [eip2612pa](https://github.com/jamiuke/EIP-2612PA) on {report['net_label']}.")
    print("\n".join(out))
